version: 2.1

jobs:
  build:
    docker:
      - image: twdps/circleci-base-image:alpine-2025.04
    resource_class: epetech/experiment
    steps:
      - checkout
      - run: echo "Hi I'm on Runners!"

workflows:
  build-workflow:
    jobs:
      - build