mode: flow
controller:
  enabled: true

flows:
  - name: gtm-flow
    spec:
      sources:
        logs:
          discovery.kubernetes:
            role: pod
        traces:
          otelcol.receiver.otlp:
            protocols:
              grpc: {}
              http: {}

      transforms:
        log_labels:
          operators:
            - type: json_parser
              source: body
            - type: add_attributes
              attributes:
                job: kubernetes

      destinations:
        loki:
          loki.write:
            endpoint: http://lgtm-loki-gateway.observability.svc.cluster.local/loki/api/v1/push

        tempo:
          otelcol.exporter.otlp:
            endpoint: http://lgtm-tempo-query-frontend.observability.svc.cluster.local:4317
            tls:
              insecure: true

      routes:
        - input: logs
          receivers: [logs]
          processors: [log_labels]
          exporters: [loki]
        - input: traces
          receivers: [traces]
          exporters: [tempo]
