kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 3000   # Grafana
      - containerPort: 30081
        hostPort: 3001   # Loki
      - containerPort: 30082
        hostPort: 3200   # Tempo
      - containerPort: 30083
        hostPort: 9090   # Prometheus