server:
  service:
    type: NodePort
    nodePort: 30083

  global:
    scrape_interval: 15s
  extraFlags:
    - web.enable-otlp-receiver
  otlp:
    promote_resource_attributes:
      - service.instance.id
      - service.name
      - service.namespace
      - service.version
      - cloud.availability_zone
      - cloud.region
      - container.name
      - deployment.environment
      - deployment.environment.name
      - k8s.cluster.name
      - k8s.container.name
      - k8s.cronjob.name
      - k8s.daemonset.name
      - k8s.deployment.name
      - k8s.job.name
      - k8s.namespace.name
      - k8s.pod.name
      - k8s.replicaset.name
      - k8s.statefulset.name
    keep_identifying_resource_attributes: true
  extraScrapeConfigs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: (.+):(?:\d+);(.+)
          replacement: $1:$2
          target_label: __address__

    - job_name: 'kubernetes-kubelet'
      scheme: https
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kind-control-plane:10250
